# Xamarin.iOS and Xamarin.Android bindings
name: 1.0.0$(rev:.r)

variables:
  PathToSrcCsproj: 'src/TrustKit.Xamarin.Core/TrustKit.Xamarin.Core.csproj'
  PathToiOSSample: 'sample/Trustkit.Forms.iOS/TrustKit.Forms.iOS.csproj'
  PathToAndroidSample: 'sample/Trustkit.Forms.Android/TrustKit.Forms.Android.csproj'

trigger:
  branches:
    include:
    - main
    - develop
  tags:
    include:
    - '*'
  paths:
    exclude:
    - README.md

pr:
  autoCancel: true
  branches:
    include:
    - main
    - develop
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'macos-latest'

steps:
# To manually select a Xamarin SDK version on the Microsoft-hosted macOS agent,
# configure this task with the *Mono* version that is associated with the
# Xamarin SDK version that you need, and set the "enabled" property to true.
# See https://go.microsoft.com/fwlink/?linkid=871629
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
  displayName: 'Select the Xamarin SDK version'
  enabled: false

- checkout: self
  lfs: true

- task: NuGetToolInstaller@1

- task: MSBuild@1
  displayName: Build TrustKit.Xamarin.Core
  inputs:
    solution: $(PathToSrcCsproj)
    configuration: Release
    msbuildArguments: '/restore /t:Build'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
    versioningScheme: 'byBuildNumber'
    configuration: Release

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '3d84ee8c-75d6-468d-83a1-d08e5e070e1d'
